---
Name: verifiable-config
---

PhpTek\Verifiable\Verify\VerifiableExtension:
  dependencies:
    verifiableService: '%$PhpTek\Verifiable\Verify\VerifiableService'
    
PhpTek\Verifiable\Controller\VerifiableController:
  dependencies:
    verifiableService: '%$PhpTek\Verifiable\Verify\VerifiableService'
    
PhpTek\Verifiable\Cron\ChainpointFullProofTask:
  dependencies:
    verifiableService: '%$PhpTek\Verifiable\Verify\VerifiableService'
    